version: 2
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    working_directory: ~/horizon-core-web

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: DockerHub Login
          command: |
            docker login -u ${dockerhub_login} -p ${dockerhub_pass}
      - run:
          name: Build and push OpenNMS Horizon Docker Image
          command: |
            DOCKERHUB_TAG=${CIRCLE_BRANCH#release/}
            DOCKERHUB_TAG=${DOCKERHUB_TAG/\//-}

            case "${CIRCLE_BRANCH}" in
              master)
                docker build -t opennms/horizon-core-web:stable .
                docker tag opennms/horizon-core-web:stable opennms/horizon-core-web:latest
                docker push opennms/horizon-core-web:stable
                docker push opennms/horizon-core-web:latest
                ;;
              *)
                docker build -t opennms/horizon-core-web:${DOCKERHUB_TAG} .
                docker push opennms/horizon-core-web:${DOCKERHUB_TAG}
                ;;
            esac
